### PR TITLE
#160845495  Enable social login

### PR DESCRIPTION
**Pull request by reiosantos**
#### What does this PR do?
- Enables a user to login with either google or facebook

#### Description of Task to be completed?
- Enable Facebook and Google authentication
- Add notification popups to notify the user on login progress
- Add loading spinner
 
image

#### How should this be manually tested?

* This feature can be manually tested by running the following 
- Run `npm install `
- Run `npm start`

#### What are the relevant pivotal tracker stories?
[#160845495](https://www.pivotaltracker.com/story/show/160845495)

### CODE REVIEW

**Comment by isheebo** [comment]
to start with, please update the screenshot to reflect the changes to the PR.


And then again, the login button, forgot password and the social login buttons are not symmetric on the page. There is an imbalance of sorts

**Comment by reiosantos** [comment]
> to start with, please update the screenshot to reflect the changes to the PR.
> 
> And then again, the login button, forgot password and the social login buttons are not symmetric on the page. There is an imbalance of sorts

Let me look through this and I will be dealing with it in a short while.

**Comment by DrKimpatrick** [comment]
Good work. Please update the screenshot to reflect the current state.

**Comment by reiosantos** [comment]
I am closing this `PR` because the changes that were proposed made have been implememted in another `PR`. You can it checkout `PR` > [PR-#26](https://github.com/andela/ah-frontend-iroquois/pull/26) for more reviews and comments.

**Pull request closed without merging**
