### PR TITLE
#160845489 Setup react router version 4

### PR DESCRIPTION
**Pull request by collinewait**
#### What does this PR do?
* It sets up react-router version 4.
#### Description of Tasks to be completed?
* Installing and configuring the router.
* Creating a dummy route for login.
* Creating a root page to test the configuration.
* Creating a components and views file structure. 
#### How should this be manually tested?
- run `npm start`  
#### What are the relevant pivotal tracker stories?

[#160845489](https://www.pivotaltracker.com/story/show/160845489)

#### Screenshots
screen shot 2018-10-01 at 23 12 20

screen shot 2018-10-01 at 23 12 07

### CODE REVIEW

**Comment by arthuroe** [comment]
@collinewait can you fix this failing build?

**Comment by collinewait** [comment]
I resolved the conflicts @arthuroe

**Comment by reiosantos** [comment]
> I resolved the conflicts @arthuroe



> I resolved the conflicts @arthuroe

LGTM

**Comment by arthuroe** [comment]
@collinewait fix conflicts

**Comment by collinewait** [comment]
I have fixed the conflicts

**Pull request merged**
